# Generated by Django 3.2.9 on 2021-12-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='subсategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Product_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя подкатегории')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subсategory', verbose_name='Название товара')),
            ],
        ),
        migrations.AddField(
            model_name='notebook',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_name', verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_name', verbose_name='Название товара'),
        ),
    ]
