# Generated by Django 4.0 on 2021-12-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211217_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='card',
            name='total_products',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
