# Generated by Django 3.2.9 on 2021-12-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_orderproduct_totalorderforuser_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorderforuser',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
