# Generated by Django 3.2.9 on 2021-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_totalorderforuser_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorderforuser',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
